Add profile information columns to user table
AmericanAirlines/Project-X pull request #26
Opened 2021-09-28 19:46 UTC by ayushagarwal0316

Adding profile information columns to user table:

### Pre-Requisites

- [ ] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [ ] Yes, I included and/or modified tests to cover relevant code **OR** my change is non-technical
- [x] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

### Description of Changes

Added columns to user table:
pronouns: text not null,
location: text,
hireable: boolean,
purpose: text not null,
schoolName: text not null,
major: text not null,
graduationDate: date not null

### Related Issues

Closes #16

2021-09-28 19:47 UTC, ayushagarwal0316 commented on packages/api/src/migrations/0000-add-the-user-table.ts
> +    //"pronouns" text not null, "location" text, "hireable" boolean, "purpose" text not null, "schoolName" text not null, "major" text not null, "graduationDate" date(0) not null
Which fields should be specified not null?
Is naming convention good?

2021-09-28 20:06 UTC, ayushagarwal0316 commented on packages/api/src/entities/User.ts
> +
Would this change be needed for the database side or would this be on the api PR #27 ?
How does typescript Date work with PostgreSQL date type?

2021-10-01 18:48 UTC, SpencerKaiser requested changes
@ayushagarwal0316 I think we didn't do a great job of explaining the DB stuff:
- The entity file for a given table _**IS**_ the table as far as you're concerned:
  - First you make an entity file
  - Next you run the commands in the README to generate a `migration`
  - You need to add a `down` method because MicroORM won't make it for you
- On changes to an entity, you modify the entity file, not the migration
- Also remember you should NEVER modify a migration after they've been created (aside from adding the `down`)
  - Migrations are only ever executed once for a DB - they get triggered and then the content they contain is applied to the DB
  - Modifying a migration in the past will execute changes out of order (migration A is run, migration B is run, and then you modify A -> that change won't ever run for your but for a new user, the changes to A may not make sense if they address things changed/created in B)

Please revert all these changes and modify the `User` entity to add the new fields to the class and to the constructor

2021-10-01 18:56 UTC, SpencerKaiser commented
@ayushagarwal0316 after reviewing your other PR, please just modify the original entity and then run the command to generate a new migration after undoing the one you already executed for your local DB.

If you have any questions, please post in Slack!

2021-10-01 18:56 UTC, closed without merging