current logged in user api
AmericanAirlines/Project-X pull request #74
Opened 2021-11-12 18:38 UTC by ntxnick

### Pre-Requisites

- [ ] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [ ] Yes, I included and/or modified tests to cover relevant code **OR** my change is non-technical
- [ ] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

### Description of Changes

Adds API to check the currently logged-in user.

### Related Issues

2021-11-16 18:02 UTC, SpencerKaiser commented
This looks like it shares a [bunch of code](https://github.com/AmericanAirlines/Project-X/pull/62/files#diff-ca9fa2ba51ed407a6e139651fdabd1c22906b0aa1e722c738a1d017599e0dad1R18-R32) from #62... marking this as draft until we get more info

2021-11-17 20:35 UTC, dre8597 approved these changes
LGTM  🚀

2021-11-22 21:27 UTC, SpencerKaiser requested changes
Quick changes and then we can merge!

2021-11-22 21:27 UTC, SpencerKaiser commented on packages/api/tests/api/users.test.ts
> +  it('401 error when not logged in', async () => {
These should always read as a sentence starting with `it`
```suggestion
  it('returns a 401 error when not logged in', async () => {
```

2021-11-22 21:27 UTC, SpencerKaiser commented on packages/api/tests/api/users.test.ts
> +  it('404 error current user not found in database', async () => {
```suggestion
  it('returns a 404 error when the current user is not found', async () => {
```

2021-11-22 21:27 UTC, SpencerKaiser commented on packages/api/tests/api/users.test.ts
> +  it('500 error during findOne', async () => {
```suggestion
  it('returns a 500 error when a database query fails', async () => {
```

2021-11-22 21:27 UTC, SpencerKaiser commented on packages/api/tests/api/users.test.ts
> +  it("Successfully send current user's information", async () => {
Also try not to use apostrophes in the description; it makes Jest very, _**very**_ unhappy sometimes
```suggestion
  it("successfully sends the data for the user when the user is logged in", async () => {
```

2021-11-22 21:49 UTC, SpencerKaiser approved these changes

2021-11-22 21:51 UTC, merged